import Image from 'next/image'
import { ArrowUpRight, Mail, MapPin, Phone } from 'lucide-react'

export function SiteHeader() { return <><div className="topbar"><div className="shell topbar-inner"><span>Trusted legal counsel in Kenya</span><span className="topbar-contact">Mon – Fri · 8:00 AM – 5:00 PM <a href="tel:+254758251399">+254 758 251 399</a></span></div></div><header className="site-header"><div className="shell nav-wrap"><a className="brand" href="/" aria-label="Musa and Musa Advocates home"><Image src="/images/logo.png" width={56} height={56} alt="Musa and Musa Advocates crest" /><span><strong>Musa &amp; Musa</strong><small>ADVOCATES</small></span></a><nav className="desktop-nav" aria-label="Primary navigation"><a href="/about">About</a><a href="/practice-areas">Practice Areas</a><a href="/team">Our Team</a><a href="/insights">Insights</a><a href="/contact">Contact</a></nav><a className="button button-dark nav-cta" href="/contact">Book a consultation <ArrowUpRight size={16} /></a></div></header></> }

export function SiteFooter() { return <footer className="footer"><div className="shell footer-grid"><div className="footer-brand"><a className="brand" href="/"><Image src="/images/logo.png" width={52} height={52} alt="Musa and Musa Advocates crest" /><span><strong>Musa &amp; Musa</strong><small>ADVOCATES</small></span></a><p>Exceptional legal services with integrity, professionalism and an unwavering dedication to justice.</p></div><div><h4>Explore</h4><a href="/about">About the firm</a><a href="/practice-areas">Practice areas</a><a href="/team">Our team</a><a href="/insights">Legal insights</a></div><div><h4>Contact</h4><a href="mailto:info@musadvocates.co.ke"><Mail size={14}/> info@musadvocates.co.ke</a><a href="tel:+254758251399"><Phone size={14}/> +254 758 251 399</a><span><MapPin size={14}/> 6076 Rhapta Road<br />Nairobi, Kenya</span></div></div><div className="shell footer-bottom"><span>© 2026 Musa &amp; Musa Advocates. All rights reserved.</span><span>Licensed to practise law in Kenya</span></div></footer> }

export function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-intro"><div className="shell"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div></section> }

export const practices = [['01','Civil Litigation','Strategic representation for disputes, contracts, property claims and commercial matters.'],['02','Criminal Defence','A considered, diligent defence from first advice through trial and appeal.'],['03','Family & Succession','Discreet guidance through divorce, custody, succession and matrimonial property matters.'],['04','Corporate & Commercial','Clear counsel for companies, entrepreneurs, contracts and business transactions.'],['05','Property & Conveyancing','Careful title reviews, land transactions, leases and conveyancing across Kenya.'],['06','Accident & Compensation','Practical representation for injury claims, including visitors and expatriates in Kenya.']] as const
export const insights = [{slug:'norwich-pharmacal-orders-kenya',title:'Norwich Pharmacal Orders in Kenya',tag:'CIVIL LITIGATION · 06 MIN READ',text:'How Kenyan courts may compel third parties to disclose information relevant to wrongdoing.'},{slug:'divorce-judicial-separation-kenya',title:'Divorce and Judicial Separation in Kenya',tag:'FAMILY LAW · 08 MIN READ',text:'A practical overview of the legal options available when a marriage breaks down.'},{slug:'enforce-foreign-judgment-kenya',title:'How to Enforce a Foreign Judgment in Kenya',tag:'CROSS-BORDER · 07 MIN READ',text:'A starting guide to documentation, jurisdiction and recognition of foreign judgments.'}]

export function PageShell({ children }: { children: React.ReactNode }) { return <><SiteHeader />{children}<SiteFooter /></> }
export function ContactCta() { return <section className="contact section"><div className="shell contact-box"><div><p className="eyebrow">START A CONVERSATION</p><h2>Let us discuss what matters to you.</h2><p>Share a little about your legal matter and our team will get back to you with the next step.</p></div><div className="contact-details"><a href="mailto:info@musadvocates.co.ke">info@musadvocates.co.ke</a><a href="tel:+254758251399">+254 758 251 399</a><span>6076 Rhapta Road, Nairobi</span><a className="button button-blue" href="/contact">Request a consultation <ArrowUpRight size={16}/></a></div></div></section> }
